name: Package Application via PyInstaller

on:
  release:
    types: [published]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile sources/FileOrganizer.py
      env:
        DISPLAY: ":99.0"

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/FileOrganizer
        asset_name: FileOrganizer
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}